import datetime
from app import db
from app.models import User, Competition, Announcement, Event

# Add users
user = User("Test", "Test", "test@test.com", "test123")
user1 = User("firstname", "lastname", "em@il.com", "password")
user2 = User("Doyle", "Achaab", "em@il2.com", "password")
user3 = User("Fanny", "Marina", "em@il3.com", "password")
user4 = User("Callie", "Garnet", "em@il4.com", "password")
user5 = User("Sylbella", "Chip", "em@il5.com", "password")
user6 = User("Laura", "Wright", "em@il6.com", "password")
user7 = User("Dave", "Zimmerman", "em@il7.com", "password")
user8 = User("Marco", "Jensen", "em@il8.com", "password")
user9 = User("Tommy", "Silva", "em@il9.com", "password")
user10 = User("Elsie", "Mitchell", "em@il10.com", "password")
user11 = User("Lenny", "Gonzalez", "em@il11.com", "password")
user12 = User("Arvis", "Peralta", "em@il12.com", "password")
user13 = User("Ichwan", "Palongengi", "em@il13.com", "password")
user14 = User("Edwin", "Zhou", "e@zhou.com", "password")

db.session.add(user)
db.session.add(user1)
db.session.add(user2)
db.session.add(user3)
db.session.add(user4)
db.session.add(user5)
db.session.add(user6)
db.session.add(user7)
db.session.add(user8)
db.session.add(user9)
db.session.add(user10)
db.session.add(user11)
db.session.add(user12)
db.session.add(user13)
db.session.add(user14)


# Add competitions
db.session.add(Competition(1, "City College Cube Day", "160 Convent Avenue", "New York", "NY", "10031", datetime.date(2017, 12, 31)))
db.session.add(Competition(user2.id, "Rubik's Cube Day", "Cubicle", "City", "State", "10009", datetime.date(2017, 12, 31)))
session_comp = Competition.query.filter_by(comp_id=1).first()
session_comp2 = Competition.query.filter_by(comp_id=2).first()

session_comp.approved = True

# Add announcement
announce = Announcement(
    session_comp.comp_id,
    user.id,
    "4x4 Evemt shorted to combined final",
    "Due to lack of time, we've shortened the 4x4 event to a combined final. We apologize for any inconvenience!"
)

db.session.add(Announcement(1, user.id, "Test Announcement", "Test Body"))
db.session.add(announce)

event = Event("Setup", "", datetime.time(8, 0, 0), datetime.time(9, 0, 0))
event1 = Event("Rubik's Cube", "Round 1", datetime.time(9, 0, 0), datetime.time(10, 0, 0))
event2 = Event("2x2x2 Cube", "Round 1", datetime.time(10, 0, 0), datetime.time(11, 0, 0))
event3 = Event("4x4x4 Cube", "Round 1", datetime.time(11, 0, 0), datetime.time(12, 0, 0))
event4 = Event("Lunch", "", datetime.time(12, 0, 0), datetime.time(13, 0, 0))
event5 = Event("Rubik's Cube", "Round 2", datetime.time(13, 0, 0), datetime.time(14, 0, 0))
event6 = Event("5x5x5 Cube", "Combined Final", datetime.time(14, 0, 0), datetime.time(15, 0, 0))
event7 = Event("6x6x6 Cube", "Combined Final", datetime.time(15, 0, 0), datetime.time(16, 0, 0))
event8 = Event("4x4x4 Cube", "Final", datetime.time(16, 0, 0), datetime.time(17, 0, 0))
event9 = Event("2x2x2", "Round 2", datetime.time(17, 0, 0), datetime.time(18, 0, 0))
event10 = Event("2x2x2", "Final", datetime.time(18, 0, 0), datetime.time(19, 0, 0))
event11 = Event("Rubik's Cube", "Final", datetime.time(19, 0, 0), datetime.time(20, 0, 0))
event12 = Event("Clean Up", "", datetime.time(20, 0, 0), datetime.time(21, 0, 0))

db.session.add(event)
db.session.add(event1)
db.session.add(event2)
db.session.add(event3)
db.session.add(event4)
db.session.add(event5)
db.session.add(event6)
db.session.add(event7)
db.session.add(event8)
db.session.add(event9)
db.session.add(event10)
db.session.add(event11)
db.session.add(event12)

session_comp.comp_events.append(event)
session_comp.comp_events.append(event1)
session_comp.comp_events.append(event2)
session_comp.comp_events.append(event3)
session_comp.comp_events.append(event4)
session_comp.comp_events.append(event5)
session_comp.comp_events.append(event6)
session_comp.comp_events.append(event7)
session_comp.comp_events.append(event8)
session_comp.comp_events.append(event9)
session_comp.comp_events.append(event10)
session_comp.comp_events.append(event11)
session_comp.comp_events.append(event12)

session_comp.competitors.append(user)
session_comp.competitors.append(user1)
session_comp.competitors.append(user2)
session_comp.competitors.append(user3)
session_comp.competitors.append(user4)
session_comp.competitors.append(user5)
session_comp.competitors.append(user6)
session_comp.competitors.append(user7)
session_comp.competitors.append(user8)
session_comp.competitors.append(user9)
session_comp.competitors.append(user10)
session_comp.competitors.append(user11)
session_comp.competitors.append(user12)
session_comp.competitors.append(user13)
session_comp.competitors.append(user14)

event1.users.append(user)
event1.users.append(user1)
event1.users.append(user2)
event1.users.append(user3)
event1.users.append(user4)
event1.users.append(user5)
event1.users.append(user6)
event1.users.append(user7)
event1.users.append(user8)
event1.users.append(user9)
event1.users.append(user10)
event1.users.append(user11)
event1.users.append(user12)
event1.users.append(user13)
event1.users.append(user14)

event2.users.append(user)
event2.users.append(user2)
event2.users.append(user4)
event2.users.append(user6)
event2.users.append(user8)
event2.users.append(user12)
event2.users.append(user10)


db.session.commit()
